deploy:
  env:
    dev: dev_bucket
    prod: prod_bucket
build:
  builtin:
    igtools: true
    epatools: # true would enable all steps
      cap_statements: true
      openapi: true
  pipeline:
    - requirements
    - sushi
    - cap_statements
    - shell: touch test.txt
    - igpub
    - openapi
