deploy:
  env:
    dev: dev_bucket
    prod: prod_bucket
build:
  builtin:
    igtools: true
    epatools: # true would enable all steps, but does not allow
      cap_statements: true
      openapi: true
      archive_files:
        - openapi.json
        - openapi.yaml
